[package]
name = "anagrams"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Generates a random word, then gets the user to guess the anagram"

[dependencies]
rand = "0.8.5"
colored = "2.1.0"